Us5
WildCodeSchool/2022-03-JS-Toulouse-project-2-actio pull request #14
Opened 2022-04-14 15:11 UTC by Mangouin

création de la page infos.jsx lié à l'US5

2022-04-14 15:19 UTC, bastienwcs requested changes

2022-04-14 15:19 UTC, bastienwcs commented on frontend/src/pages/Infos.css
> +  margin: 0 2rem 0 2rem;
peut être simplifié en margin: 0 2rem;

2022-04-14 15:20 UTC, bastienwcs requested changes

2022-04-14 15:20 UTC, bastienwcs commented on frontend/src/pages/Infos.jsx
> +            src="/src/assets/location icone.svg"
pas d'espace dans les noms de fichiers, à corriger sur tous les fichiers et appels de fichiers

2022-04-15 05:56 UTC, ymblandin approved these changes

2022-04-15 06:50 UTC, bastienwcs commented
Il ne reste plus qu'à renommer les fichiers et appels de fichiers avec un espace, et je valide :+1:

2022-04-15 07:38 UTC, bastienwcs approved these changes
C'est validé :+1:

2022-04-15 07:41 UTC, merged