Us12 another new quiz
WildCodeSchool/2022-03-JS-Toulouse-project-2-actio pull request #35
Opened 2022-04-28 15:27 UTC by IrnehBrgt

2022-04-28 15:29 UTC, ymblandin approved these changes
Bien joué !

2022-04-29 08:05 UTC, bastienwcs requested changes

2022-04-29 08:05 UTC, bastienwcs commented on package.json
> +    "react-router-dom": "^6.3.0"
il ne faut pas modifier le packages.Json de la racine.

Supprime le block "dependencies" et refait un "npm install" avant de add / commit / push

2022-04-29 08:20 UTC, bastienwcs approved these changes

2022-04-29 08:40 UTC, merged