US15 images changing according sport selected
WildCodeSchool/2022-03-JS-Toulouse-project-2-actio pull request #37
Opened 2022-04-29 09:01 UTC by Mangouin

2022-04-29 12:32 UTC, IrnehBrgt approved these changes

2022-05-04 08:34 UTC, IrnehBrgt approved these changes

2022-05-04 08:42 UTC, bastienwcs requested changes

2022-05-04 08:42 UTC, bastienwcs commented on .vscode/settings.json
> +{
fichier de configuration à supprimer, ensuite ajouter .vscode dans le .gitignore de la racine 

`git rm .vscode/settings.json`

2022-05-04 08:42 UTC, bastienwcs commented on frontend/src/App.jsx
> +const selectedLocation = {
variable non utilisée, la supprimer

2022-05-04 12:54 UTC, Mangouin reviewed
selectedLocation deleted

2022-05-04 13:10 UTC, merged